apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tdql4upvt-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tdql4upvt-java-springboot-gitops